// Generates src/styles/framework/global.grid.css (Raster-style attribute grid).
// The enumerated col/span selectors are mechanical; edit this generator and
// re-run it (node src/tools/generate.global.grid.cjs), never the output.
//
// Tiers: the bare col/span attributes are mobile-first defaults; responsive
// variants exist for md/lg/xl only (col-md, span-lg, ...). Selector order is
// load-bearing: [span^="1"] also matches "12...", so higher numbers must come
// later to win.

const COLS = 24;

const TIERS = [
  { suffix: "", comment: "/* DEFAULT */" },
  { suffix: "-md", comment: "/* MD — window >= 768px */", media: "--md-n-above" },
  { suffix: "-lg", comment: "/* LARGE -  width >= 1024 */", media: "--lg-n-above" },
  { suffix: "-xl", comment: "/* EXTRA LARGE -  width >= 1440 */", media: "--xl-n-above" },
];

const range = (n) => Array.from({ length: n }, (_, i) => i + 1);

function colRules(suffix, indent) {
  return range(COLS)
    .map((n) => `${indent}.grid[col${suffix}="${n}"] { --grid-tc: repeat(${n}, 1fr) }`)
    .join("\n");
}

function spanStartRules(suffix, indent) {
  return range(COLS)
    .map((n) => `${indent}.grid > .grid_item[span${suffix}^="${n}"] { --grid-cs: ${n} }`)
    .join("\n");
}

function spanEndRules(suffix, indent) {
  const item = (sel) => `.grid > .grid_item[span${suffix}${sel}]`;
  const lines = range(COLS).map((n) => {
    const parts = [item(`$="+${n}"`)];
    if (n > 1) parts.push(item(`$="-${n - 1}"`));
    parts.push(item(`="${n}"`));
    return `${indent}${parts.join(", ")} { --grid-ce: ${n} }`;
  });
  lines.push(`${indent}${item(`$="-${COLS}"`)}${suffix === "" ? " " : ""} { --grid-ce: ${COLS + 1} }`);
  return lines.join("\n");
}

function connectRules(suffix, indent) {
  const item = (sel) => `.grid > .grid_item[span${suffix}${sel}]`;
  return [
    `${indent}${item("")} { grid-column-end: span var(--grid-ce) }`,
    `${indent}${item('*="+"')}, ${item('*="-"')}, ${item('*=".."')} {`,
    `${indent}  grid-column-start: var(--grid-cs) }`,
    `${indent}${item('*="-"')}, ${item('*=".."')} {`,
    `${indent}  grid-column-end: var(--grid-ce) }`,
    `${indent}${item('="row"')} { grid-column: 1 / -1 }`,
  ].join("\n");
}

function tierBlock({ suffix, comment, media }) {
  const indent = media ? "  " : "";
  const body = [
    media ? "" : `.grid > .grid_item { display: block; -moz-appearance: none; appearance: none; -webkit-appearance: none }`,
    colRules(suffix, indent),
    media ? "" : null,
    `${indent}/* span${suffix}=start... */`,
    spanStartRules(suffix, indent),
    media ? "" : null,
    `${indent}/* span${suffix}=...+width, span${suffix}=...-end */`,
    spanEndRules(suffix, indent),
    media ? "" : null,
    `${indent}/* connect vars */`,
    connectRules(suffix, indent),
  ]
    .filter((x) => x !== null)
    .join("\n")
    .replace(/\n\n\n+/g, "\n\n");

  if (media) {
    return `${comment}\n@media only screen and (${media}) {\n${body.replace(/^\n/, "")}\n}`;
  }
  return `${comment}\n${body}`;
}

const HEADER = `/* GRID */
/* Generated by src/tools/generate.global.grid.cjs */
.grid {
  display: grid;
  --grid-tc: repeat(4, 1fr);
  --grid-cs: 1; /* column start */
  --grid-ce: -1; /* column end */
  grid-template-columns: var(--grid-tc);
  grid-column-gap: var(--grid-column-gap);
  grid-row-gap: var(--grid-row-gap);
}

.grid-flush {
  grid-column-gap: 0;
  grid-row-gap: 0;
}
`;

const css = [HEADER, ...TIERS.map(tierBlock)].join("\n") + "\n";

const fs = require("fs");
const path = require("path");
const out = path.join(__dirname, "../styles/framework/global.grid.css");
fs.writeFileSync(out, css);
console.log(`Wrote ${out} (${css.split("\n").length} lines)`);
